/**
 * Interface for tracking changes since last documentation update
 */
export interface ChangesSinceLastUpdate {
    changedFiles: string[];
    addedFiles: string[];
    deletedFiles: string[];
    lastUpdateTime: Date;
}

/**
 * Interface for documentation files generated by the system
 */
export interface DocumentationFile {
    path: string;
    content: string;
    type: 'readme' | 'api' | 'changelog' | 'other';
}
